const CustomerActionTypes = {
  FETCH_CUSTOMER_START: 'FETCH_CUSTOMER_START',
  FETCH_CUSTOMER_SUCCESS: 'FETCH_CUSTOMER_SUCCESS',
  FETCH_CUSTOMER_FAILURE: 'FETCH_CUSTOMER_FAILURE',
  SET_CUSTOMER_SUCCESS: 'SET_CUSTOMER_SUCCESS',
  SET_CUSTOMER_OPTION_SELECTED: 'SET_CUSTOMER_OPTION_SELECTED',
  UPDATE_CUSTOMER_BY_NAME_VALUE: 'UPDATE_CUSTOMER_BY_NAME_VALUE',
};

export default CustomerActionTypes;
