const CustomerActionTypes = {
  FETCH_CUSTOMER_START: 'FETCH_CUSTOMER_START',
  FETCH_CUSTOMER_SUCCESS: 'FETCH_CUSTOMER_SUCCESS',
  FETCH_CUSTOMER_FAILURE: 'FETCH_CUSTOMER_FAILURE'
};

export default CustomerActionTypes;
