const CustomerActionTypes = {
  FETCH_CUSTOMER_START: 'FETCH_CUSTOMER_START',
  FETCH_CUSTOMER_SUCCESS: 'FETCH_CUSTOMER_SUCCESS',
  FETCH_CUSTOMER_FAILURE: 'FETCH_CUSTOMER_FAILURE',
  SET_CUSTOMER_SUCCESS: 'SET_CUSTOMER_SUCCESS'
};

export default CustomerActionTypes;
